.github/actions/derive-docker-name/index.js
Check if this property is an option to use instead of scanning
=> YM-3502 Attempt to fix scan

.github/workflows/step-service-build.yml
* Typo: change "input.python-version" to "inputs.python-version"
=> YM-3329 Update step-service-build.yml

update-cluster-version/action.yaml
Don't use interpolation characters in descriptions
=> DOP-751 Update cluster version action

docker-build-and-push/action.yml
=> DOP-808 Fix suppress release

.github/dependabot.yml, .github/workflows/step-service-check.yml
- Custom Python version in check flow
- Dependabot config
=> YM-4009 Custom Python Version For Check

.github/dependabot.yml
Add Dependabot for derive docker name step
=> YM-293 Add Dependabot for derive docker name step

trivy-scan/action.yml
* Allows for the use of trivy "ignore files" to accept CVEs as incidental.
* Updates and allows the version of the trivy-action to be overridden.
=> DOP-823 Add trivyignores

trivy-scan/action.yml
trivy action _tags_ are sans v
=> DOP-827 Fix scan version

trivy-scan/action.yml
=> DOP-830 Fix trivy typo

launch-self-hosted-runner/action.yml
Missing a `shell` attribute for a run step
=> DOP-846 Fix GHA self-host-runners

nix-shell-docker/action.yml, push-archive/action.yml
`kcadm` and `vault-setup` are built using Nix expressions; very small, very limited containers.
Standardizing the functionality here.
=> DOP-871 Add nix-shell build

launch-self-hosted-runner/action.yml
=> DOP-882 Update gha runner

nix-shell-docker/action.yml, push-archive/action.yml
Fixes to nix based docker image builds
=> DOP-874 Fix nix docker

nix-shell-docker/action.yml, update-flakes/action.yml
Commit to new-style nix "flakes" (auto-update, pinned)
=> DOP-884 Modernize nix

update-flakes/action.yml
Incorporates a stub Github App so that both these things can be true:
* The update commits are verified
* The PRs trigger further actions (like Trivy scans)
=> DOP-888 Nix best of both

.github/workflows/step-service-build.yml, .github/workflows/step-service-check.yml, .github/workflows/step-service-scan.yml
=> YM-4285 BE: The GitHub Actions For Steps Should Ignore Secrets In Python Libraries

launch-self-hosted-runner/action.yml
Bring GHA self-hosted up to date
=> DOP-933 Update step runner

nix-shell-docker/action.yml
Excluding secrets from scanning for containers we build with upstream software
=> DOP-973 Exclude secret scanning

launch-self-hosted-runner/action.sh, launch-self-hosted-runner/action.yml
Add local_ssd
Needs an alternative
Needs base runner version updated
n.b. probably not done building, but is building
=> DOP-981 Nvme jobs

.github/workflows/step-service-build.yml, .github/workflows/step-service-check.yml
Some steps may have LFS files in them. We will need to check these out for the build.
=> INTG-428 Support LFS files in steps

.github/workflows/step-service-scan.yml
=> Ignore python libs during scan

docker-build-and-push/action.yml, launch-self-hosted-runner/action.yml, lib/setup-gcr/action.yml, nix-shell-docker/action.yml, update-flakes/action.yml
- Updating Nix actions
- Update version of actions (esp. google-github-actions/*)
- Update version of GHA runner
=> DOP-1152 Update Github Actions

launch-self-hosted-runner/action.yml
=> DOP-1164 Upgrade GHA runner to 0.304

nix-shell-docker/action.yml, push-archive/action.yml
Add hook to allow projects to describe their own build process
Remove old Demo environment
=> DOP-1185 Update nix tools

launch-self-hosted-runner/action.yml
Time again to update our GHA runner version
=> DOP-1198 Update GHA runner to 2.307

launch-self-hosted-runner/action.yml
=> GHA Runner -> 2.309.0

.github/actions/setup-sonarcloud/index.js
Switch to form encoding for call to Sonar to use form encoding
Fix header logging
Add accept JSON header
=> YM-5318 Switch to form encoding

.github/actions/setup-sonarcloud/index.js
=> YM-5318 Always set key as output

.github/workflows/step-service-check.yml
=> YM-5318 Write sonar.properties

.github/workflows/step-service-build.yml
=> YM-5322 Add labels to the push command

.github/workflows/step-service-build.yml
Use a fork of the action that has a branch using Python 3.11
=> YM-5322 Use Python 3.11 Y Meadows fork

.github/workflows/step-service-build.yml, .github/workflows/step-service-check.yml, .github/workflows/step-service-scan.yml
=> YM-5809 fix CVE number

.github/workflows/step-service-build.yml, .github/workflows/step-service-check.yml, .github/workflows/step-service-scan.yml
=> YM-5809 Handle both CVEs

launch-self-hosted-runner/action.yml
=> Update to 2.314.1

launch-self-hosted-runner/action.yml
./PULL_REQUEST_TEMPLATE/pull_request_template.md
=> DOP-1424 Update runner to 2.316.1

.github/workflows/step-service-build.yml, .github/workflows/step-service-check.yml
Upgrade docker build step to v6
=> YM-293 Docker v6

.github/workflows/step-service-check.yml
Remove broken auto-merge feature
=> YM-293 remove broken auto-merge code

.github/workflows/step-service-build.yml, .github/workflows/step-service-check.yml
=> YM-6676 Pre-install gcloud for step's GA

.github/workflows/step-service-check.yml
=> YM-7017 Upgrade Sonar GHA

.github/workflows/step-service-build.yml, .github/workflows/step-service-check.yml, .github/workflows/step-service-scan.yml
=> Exclude minor CVEs

.github/workflows/step-service-check.yml
Fix an issue where the Trivy DB is not cached
=> Fix an issue where the Trivy DB is not cached

update-flakes/action.yml, update-flakes/nix-update.sh
- **feat: regexes for packages and blacklists **
- **fix: GHA syntax **
=> DOP-1606 Make package hash update optional

launch-self-hosted-runner/action.sh
=> DOP-1666 Fix GCP runner

update-version/action.yaml
=> DOP-1694 Make cluster update generic

lib/setup-gcr/action.yml
- **feat: add "gha-creds" pattern to .gitignore and .dockerignore**
- **fix: YAML indents**
=> DOP-1728 Fix indentation

.github/workflows/step-service-build.yml, .github/workflows/step-service-check.yml
Switch to use tarballs for trivy
=> Switch to use tarballs for trivy

.github/workflows/step-service-build.yml, .github/workflows/step-service-check.yml
=> Try tarball again

.github/workflows/step-service-check.yml
=> Attempts to fix the trivy os detection

.github/workflows/step-service-check.yml
=> Try direct CLI commands

.github/workflows/step-service-check.yml
=> Fix syntax

.github/workflows/step-service-build.yml, .github/workflows/step-service-check.yml
=> Fix trivy and tag images

.github/actions/setup-sonarcloud/node_modules/@actions/core/lib/oidc-utils.js, push-archive-to-registry/action.yml, push-archive/action.yml
=> DOP-1797 Add Ops repo for push
